#!/bin/bash
 
py_2=$(python --version 2>&1 | egrep -o "[0-9].[0-9].[0-9]")
py_3=$(python3 --version | egrep -o "[0-9].[0-9].[0-9]")

echo "Python 2 version $py_2"
echo "Python 3 version $py_3"

if [ $py_2 \> $py_3 ]
then
echo "So $py_2 is greater than $py_3"
else
echo "So $py_2 is less than $py_3"
fi

